local folderName, DTC = ...
DTC.L = {}

-- Metatable to return the key itself if translation is missing
setmetatable(DTC.L, {
    __index = function(t, k) return k end
})

-- General
DTC.L["General"] = "General"
DTC.L["Nicknames"] = "Nicknames"
DTC.L["Leaderboard"] = "Leaderboard"
DTC.L["History"] = "History"
DTC.L["Voting"] = "Voting"
DTC.L["Bribes"] = "Bribes"
DTC.L["General Options"] = "General Options"
DTC.L["Test Vote Window"] = "Test Vote Window"
DTC.L["Test Leaderboard"] = "Test Leaderboard"
DTC.L["Test History"] = "Test History"
DTC.L["Test Incoming Bribe"] = "Test Incoming Bribe"
DTC.L["Test Proposition"] = "Test Proposition"
DTC.L["Test Lobbying"] = "Test Lobbying"
DTC.L["Test Debts"] = "Test Debts"
DTC.L["Version Check"] = "Version Check"
DTC.L["Reset to Defaults"] = "Reset to Defaults"
DTC.L["Force Start Session"] = "Force Start Session"

-- Nicknames
DTC.L["Roster Configuration"] = "Roster Configuration"
DTC.L["Select All"] = "Select All"
DTC.L["Delete Selected"] = "Delete Selected"
DTC.L["No Guild"] = "No Guild"

-- Leaderboard
DTC.L["Leaderboard Options"] = "Leaderboard Options"
DTC.L["Detail Level:"] = "Detail Level:"
DTC.L["Show All Votes"] = "Show All Votes"
DTC.L["Show Only Nickname"] = "Show Only Nickname"
DTC.L["Award Configuration"] = "Award Configuration"
DTC.L["Winning Message (%s = Name):"] = "Winning Message (%s = Name):"

-- History
DTC.L["Database Maintenance"] = "Database Maintenance"
DTC.L["Reset Local Data"] = "Reset Local Data"
DTC.L["Open Bribe Ledger"] = "Open Bribe Ledger"
DTC.L["All Raids"] = "All Raids"
DTC.L["All Exp"] = "All Exp"
DTC.L["All"] = "All"
DTC.L["All Dates"] = "All Dates"
DTC.L["Sync Data"] = "Sync Data"
DTC.L["Target Player:"] = "Target Player:"
DTC.L["Push Data"] = "Push Data"
DTC.L["Purge Data"] = "Purge Data"
DTC.L["Purge Matching"] = "Purge Matching"
DTC.L["Permanently delete matching entries?"] = "Permanently delete matching entries?"
DTC.L["Yes"] = "Yes"
DTC.L["No"] = "No"

-- Voting
DTC.L["Voting Options"] = "Voting Options"
DTC.L["List Format:"] = "List Format:"
DTC.L["Show Players and Roles"] = "Show Players and Roles"
DTC.L["Show Only Players"] = "Show Only Players"
DTC.L["Voting Window Duration"] = "Voting Window Duration"
DTC.L["Votes Per Person"] = "Votes Per Person"
DTC.L["Reset Defaults"] = "Reset Defaults"
DTC.L["Announce Messages"] = "Announce Messages"
DTC.L["Active Message Count"] = "Active Message Count"
DTC.L["Test Announcement"] = "Test Announcement"
DTC.L["Test Message %s"] = "Test Message %s"
DTC.L["Runner Up Message:"] = "Runner Up Message:"
DTC.L["Lowest Vote Message:"] = "Lowest Vote Message:"
DTC.L["Enable"] = "Enable"
DTC.L["Secure Mode (Leader Only Start)"] = "Secure Mode (Leader Only Start)"
DTC.L["|cFFFFD700DTC:|r Voting settings reset to defaults."] = "|cFFFFD700DTC:|r Voting settings reset to defaults."

-- Bribes
DTC.L["Timer Settings"] = "Timer Settings"
DTC.L["Bribe Offer Expiration"] = "Bribe Offer Expiration"
DTC.L["Proposition Expiration"] = "Proposition Expiration"
DTC.L["Lobbying Expiration"] = "Lobbying Expiration"
DTC.L["State Corruption Fee (%)"] = "State Corruption Fee (%)"
DTC.L["Debt Management"] = "Debt Management"
DTC.L["Announce Debts"] = "Announce Debts"
DTC.L["Debt Limit (Gold, 0 = No Limit):"] = "Debt Limit (Gold, 0 = No Limit):"

-- Popups
DTC.L["Reset ALL data? This cannot be undone."] = "Reset ALL data? This cannot be undone."
DTC.L["|cFFFFD700DTC:|r Database reset."] = "|cFFFFD700DTC:|r Database reset."
DTC.L["Are you sure you want to forgive this debt?"] = "Are you sure you want to forgive this debt?"
DTC.L["Mark this debt as PAID? (No gold will be traded)"] = "Mark this debt as PAID? (No gold will be traded)"
DTC.L["Reset all configuration settings to defaults?"] = "Reset all configuration settings to defaults?"
DTC.L["|cFFFFD700DTC:|r Settings reset to defaults."] = "|cFFFFD700DTC:|r Settings reset to defaults."
DTC.L["Clear all bribe ledger entries? This cannot be undone."] = "Clear all bribe ledger entries? This cannot be undone."
DTC.L["Do you want to activate DTC Raid Tracker for this raid?"] = "Do you want to activate DTC Raid Tracker for this raid?"
DTC.L["|cFF00FF00DTC:|r Session started."] = "|cFF00FF00DTC:|r Session started."
DTC.L["|cFFFF0000DTC:|r Session disabled."] = "|cFFFF0000DTC:|r Session disabled."
DTC.L["Force start a new session? This will re-prompt everyone."] = "Force start a new session? This will re-prompt everyone."

-- Bribe UI
DTC.L["DTC Tracker - Bribe Offer"] = "DTC Tracker - Bribe Offer"
DTC.L["Enter Amount for %s (Gold):"] = "Enter Amount for %s (Gold):"
DTC.L["Proposition Bribe"] = "Proposition Bribe"
DTC.L["DTC Tracker - Proposition"] = "DTC Tracker - Proposition"
DTC.L["DTC Tracker - Incoming Bribe"] = "DTC Tracker - Incoming Bribe"
DTC.L["|cFFFFD700%s|r offers you |cFFFFD700%s Gold|r"] = "|cFFFFD700%s|r offers you |cFFFFD700%s Gold|r"
DTC.L["DTC Tracker - Bribe Ledger"] = "DTC Tracker - Bribe Ledger"
DTC.L["My Debts"] = "My Debts"
DTC.L["Debts Owed to Me"] = "Debts Owed to Me"
DTC.L["Date (Newest)"] = "Date (Newest)"
DTC.L["Date (Oldest)"] = "Date (Oldest)"
DTC.L["Amount (High)"] = "Amount (High)"
DTC.L["Amount (Low)"] = "Amount (Low)"
DTC.L["All Names"] = "All Names"
DTC.L["Total Debt: %s"] = "Total Debt: %s"
DTC.L["Export CSV"] = "Export CSV"
DTC.L["Mark Taxes Paid"] = "Mark Taxes Paid"
DTC.L["Marks all 'Corruption Fee' debts owed to you as PAID."] = "Marks all 'Corruption Fee' debts owed to you as PAID."
DTC.L["Use this after collecting gold from the mailbox or trade."] = "Use this after collecting gold from the mailbox or trade."
DTC.L["Select Candidate"] = "Select Candidate"
DTC.L["Select a candidate."] = "Select a candidate."
DTC.L["Lobbying"] = "Lobbying"
DTC.L["DTC Tracker - Lobby"] = "DTC Tracker - Lobby"
DTC.L["|cFFFFD700%s|r pays |cFFFFD700%sg|r for |cFF00FF00%s|r"] = "|cFFFFD700%s|r pays |cFFFFD700%sg|r for |cFF00FF00%s|r"
DTC.L["Export Bribe Ledger (Ctrl+C)"] = "Export Bribe Ledger (Ctrl+C)"
DTC.L["Forgive"] = "Forgive"
DTC.L["Mark Paid"] = "Mark Paid"
DTC.L["|cFF00FF00PAID|r"] = "|cFF00FF00PAID|r"
DTC.L["|cFFFF0000OWED|r"] = "|cFFFF0000OWED|r"

-- Bribe Messages
DTC.L["|cFFFF0000DTC:|r Bribes are only available in a raid group (or Solo for testing)."] = "|cFFFF0000DTC:|r Bribes are only available in a raid group (or Solo for testing)."
DTC.L["|cFFFF0000DTC:|r Unpaid debts exist!"] = "|cFFFF0000DTC:|r Unpaid debts exist!"
DTC.L["|cFFFF0000DTC:|r Cannot offer bribe. Total debt exceeds limit (%sg)."] = "|cFFFF0000DTC:|r Cannot offer bribe. Total debt exceeds limit (%sg)."
DTC.L["|cFF00FF00DTC:|r Offered %sg to %s"] = "|cFF00FF00DTC:|r Offered %sg to %s"
DTC.L["|cFFFF0000DTC:|r Voting has ended. Offer expired."] = "|cFFFF0000DTC:|r Voting has ended. Offer expired."
DTC.L["|cFFFF0000DTC:|r Unpaid debts exist! Cannot incur tax."] = "|cFFFF0000DTC:|r Unpaid debts exist! Cannot incur tax."
DTC.L["|cFFFF0000DTC:|r Cannot accept offer. Total debt exceeds limit (%sg)."] = "|cFFFF0000DTC:|r Cannot accept offer. Total debt exceeds limit (%sg)."
DTC.L["|cFF00FF00DTC:|r Accepted bribe from %s"] = "|cFF00FF00DTC:|r Accepted bribe from %s"
DTC.L["|cFFFF0000DTC:|r Propositions are only available in a raid group (or Solo for testing)."] = "|cFFFF0000DTC:|r Propositions are only available in a raid group (or Solo for testing)."
DTC.L["Voting is closed."] = "Voting is closed."
DTC.L["No votes left to sell!"] = "No votes left to sell!"
DTC.L["|cFFFF0000DTC:|r Cannot send proposition. Total debt exceeds limit (%sg)."] = "|cFFFF0000DTC:|r Cannot send proposition. Total debt exceeds limit (%sg)."
DTC.L["|cFF00FF00DTC:|r Proposition broadcast: My vote for %sg."] = "|cFF00FF00DTC:|r Proposition broadcast: My vote for %sg."
DTC.L["|cFFFF0000DTC:|r Cannot accept proposition. Total debt exceeds limit (%sg)."] = "|cFFFF0000DTC:|r Cannot accept proposition. Total debt exceeds limit (%sg)."
DTC.L["|cFF00FF00DTC:|r Proposition accepted by %s. Vote cast!"] = "|cFF00FF00DTC:|r Proposition accepted by %s. Vote cast!"
DTC.L["|cFFFF0000DTC:|r Lobbying is only available in a raid group (or Solo for testing)."] = "|cFFFF0000DTC:|r Lobbying is only available in a raid group (or Solo for testing)."
DTC.L["|cFFFF0000DTC:|r You cannot lobby for yourself."] = "|cFFFF0000DTC:|r You cannot lobby for yourself."
DTC.L["|cFFFF0000DTC:|r Unpaid debts exist! Cannot incur debt/tax."] = "|cFFFF0000DTC:|r Unpaid debts exist! Cannot incur debt/tax."
DTC.L["|cFFFF0000DTC:|r Cannot lobby. Total debt exceeds limit (%sg)."] = "|cFFFF0000DTC:|r Cannot lobby. Total debt exceeds limit (%sg)."
DTC.L["|cFF00FF00DTC:|r Lobbying for %s (%sg) broadcast to raid."] = "|cFF00FF00DTC:|r Lobbying for %s (%sg) broadcast to raid."
DTC.L["|cFFFF0000DTC:|r Voting has ended."] = "|cFFFF0000DTC:|r Voting has ended."
DTC.L["|cFF00FF00DTC:|r Accepted Lobby from %s to vote for %s"] = "|cFF00FF00DTC:|r Accepted Lobby from %s to vote for %s"
DTC.L["|cFFFF0000DTC:|r Cannot initiate trade in combat."] = "|cFFFF0000DTC:|r Cannot initiate trade in combat."
DTC.L["|cFFFF0000DTC:|r Cannot initiate trade while dead."] = "|cFFFF0000DTC:|r Cannot initiate trade while dead."
DTC.L["|cFFFF0000DTC:|r Cannot trade: Unit '%s' not found in group or target."] = "|cFFFF0000DTC:|r Cannot trade: Unit '%s' not found in group or target."
DTC.L["|cFF00FF00DTC:|r No outstanding debts found."] = "|cFF00FF00DTC:|r No outstanding debts found."
DTC.L["--- DTC Debt Report ---"] = "--- DTC Debt Report ---"
DTC.L["|cFFFF0000DTC:|r You must be in a raid group to mark taxes as paid (to ensure sync)."] = "|cFFFF0000DTC:|r You must be in a raid group to mark taxes as paid (to ensure sync)."
DTC.L["|cFF00FF00DTC:|r Marked %d tax debts as paid."] = "|cFF00FF00DTC:|r Marked %d tax debts as paid."
DTC.L["|cFFFF0000DTC:|r No outstanding tax debts found."] = "|cFFFF0000DTC:|r No outstanding tax debts found."
DTC.L["|cFFFF0000DTC:|r You must be in a raid group to forgive debts."] = "|cFFFF0000DTC:|r You must be in a raid group to forgive debts."
DTC.L["|cFF00FF00DTC:|r You forgave the debt of %s (%sg)."] = "|cFF00FF00DTC:|r You forgave the debt of %s (%sg)."
DTC.L["|cFFFF0000DTC:|r You must be in a raid group to mark debts as paid."] = "|cFFFF0000DTC:|r You must be in a raid group to mark debts as paid."
DTC.L["|cFF00FF00DTC:|r Manually marked debt from %s as PAID."] = "|cFF00FF00DTC:|r Manually marked debt from %s as PAID."

-- Vote Messages
DTC.L["|cFFFF0000DTC:|r You cannot vote for yourself."] = "|cFFFF0000DTC:|r You cannot vote for yourself."
DTC.L["Voting has been finalized for %s!"] = "Voting has been finalized for %s!"
DTC.L["--- DTC Results: %s ---"] = "--- DTC Results: %s ---"
DTC.L["%d. %s (%d pts)"] = "%d. %s (%d pts)"
DTC.L["Congrats %s!"] = "Congrats %s!"

-- Leaderboard UI
DTC.L["|cFFFF0000DTC:|r Cannot award in Test Mode."] = "|cFFFF0000DTC:|r Cannot award in Test Mode."
DTC.L["--- DTC TRIP AWARDED ---"] = "--- DTC TRIP AWARDED ---"

-- History UI
DTC.L["Export Data (Ctrl+C)"] = "Export Data (Ctrl+C)"
DTC.L["DTC Tracker - History"] = "DTC Tracker - History"
DTC.L["Date"] = "Date"
DTC.L["Raid"] = "Raid"
DTC.L["Diff"] = "Diff"
DTC.L["Boss"] = "Boss"
DTC.L["Winner"] = "Winner"
DTC.L["Voters"] = "Voters"
DTC.L["(Test) "] = "(Test) "
DTC.L["None"] = "None"

-- Vote Frame
DTC.L["DTC Tracker - Vote"] = "DTC Tracker - Vote"
DTC.L["Unknown Boss"] = "Unknown Boss"
DTC.L["Votes: "] = "Votes: "
DTC.L["CLOSED"] = "CLOSED"
DTC.L["TANKS"] = "TANKS"
DTC.L["HEALERS"] = "HEALERS"
DTC.L["DPS / OTHERS"] = "DPS / OTHERS"
DTC.L["Vote"] = "Vote"
DTC.L["Bribe"] = "Bribe"
DTC.L["Lobby"] = "Lobby"

-- Static Data (Expansions & Difficulties)
DTC.L["Classic"] = "Classic"
DTC.L["Burning Crusade"] = "Burning Crusade"
DTC.L["Wrath of the Lich King"] = "Wrath of the Lich King"
DTC.L["Cataclysm"] = "Cataclysm"
DTC.L["Mists of Pandaria"] = "Mists of Pandaria"
DTC.L["Warlords of Draenor"] = "Warlords of Draenor"
DTC.L["Legion"] = "Legion"
DTC.L["Battle for Azeroth"] = "Battle for Azeroth"
DTC.L["Shadowlands"] = "Shadowlands"
DTC.L["Dragonflight"] = "Dragonflight"
DTC.L["The War Within"] = "The War Within"
DTC.L["Midnight"] = "Midnight"

DTC.L["Normal"] = "Normal"
DTC.L["Heroic"] = "Heroic"
DTC.L["Mythic"] = "Mythic"
DTC.L["LFR"] = "LFR"
DTC.L["10m Normal"] = "10m Normal"
DTC.L["25m Normal"] = "25m Normal"
DTC.L["10m Heroic"] = "10m Heroic"
DTC.L["25m Heroic"] = "25m Heroic"
DTC.L["Unknown"] = "Unknown"

-- History Models
DTC.L["Invalid target."] = "Invalid target."
DTC.L["|cFFFFD700DTC:|r Sending data to %s..."] = "|cFFFFD700DTC:|r Sending data to %s..."
DTC.L["|cFFFFD700DTC:|r Sent %d entries."] = "|cFFFFD700DTC:|r Sent %d entries."
DTC.L["|cFFFFD700DTC:|r Purged %d entries."] = "|cFFFFD700DTC:|r Purged %d entries."
DTC.L["|cFF00FF00DTC:|r Received entry from %s"] = "|cFF00FF00DTC:|r Received entry from %s"